- frontend/mgramseva/lib/main.dart
- frontend/mgramseva/lib/model/localization/language.dart
- frontend/mgramseva/lib/model/user/user_details.dart
- frontend/mgramseva/lib/model/userProfile/user_profile.dart
- frontend/mgramseva/lib/providers/common_provider.dart
- frontend/mgramseva/lib/providers/language.dart
- frontend/mgramseva/lib/providers/user_profile_provider.dart
- frontend/mgramseva/lib/repository/core_repo.dart
- frontend/mgramseva/lib/repository/user_profile_repo.dart
- frontend/mgramseva/lib/router.dart
- frontend/mgramseva/lib/routers/Routers.dart
- frontend/mgramseva/lib/screeens/Changepassword.dart
- frontend/mgramseva/lib/screeens/EditProfile.dart
- frontend/mgramseva/lib/screeens/Profile/EditProfile.dart
- frontend/mgramseva/lib/services/urls.dart
- frontend/mgramseva/lib/utils/constants.dart
- frontend/mgramseva/lib/widgets/RadioButtonFieldBuilder.dart
- frontend/mgramseva/lib/widgets/SideBar.dart
> Mgramchanges 102

- frontend/mgramseva/lib/screeens/Login/Login.dart
- frontend/mgramseva/lib/utils/Constants/I18KeyConstants.dart
Created a Const file which can be updated with i18 keys
> extracted i18keys

- frontend/mgramseva/lib/model/expensesDetails/expenses_details.dart
- frontend/mgramseva/lib/model/expensesDetails/expenses_details.g.dart
- frontend/mgramseva/lib/providers/expenses_details_provider.dart
- frontend/mgramseva/lib/repository/expenses_repo.dart
- frontend/mgramseva/lib/router.dart
- frontend/mgramseva/lib/screeens/ExpenseDetails.dart
- frontend/mgramseva/lib/screeens/expense/expense_results.dart
- frontend/mgramseva/lib/screeens/expense/search_expense.dart
- frontend/mgramseva/lib/services/urls.dart
- frontend/mgramseva/lib/utils/Constants/I18KeyConstants.dart
- frontend/mgramseva/lib/utils/common_widgets.dart
- frontend/mgramseva/lib/utils/models.dart
- frontend/mgramseva/lib/widgets/SelectFieldBuilder.dart
- frontend/mgramseva/lib/widgets/TextFieldBuilder.dart
For reference [https://digit-discuss.atlassian.net/browse/IFIX-154?atlOrigin=eyJpIjoiYjhjNmRjY2FjZDNhNDI1ZDg3ZDdmZDgzNTc5OTEwYjMiLCJwIjoiaiJ9](url)
> IFIX 154 - UI : Search Expenses API integration 

- frontend/mgramseva/lib/providers/expenses_details_provider.dart
- frontend/mgramseva/lib/screeens/AddExpense/ExpenseDetails.dart
[Jira reference ticket](https://digit-discuss.atlassian.net/browse/IFIX-334?atlOrigin=eyJpIjoiMWNlZjBjNTZjZTkwNDEwMjhhNWYwNjA1N2MxMTAyY2QiLCJwIjoiaiJ9)
> IFIX-334 : Mark this bill as cancelled must be aligned 

- frontend/mgramseva/lib/screeens/expense/expense_results.dart
- frontend/mgramseva/lib/utils/Constants/I18KeyConstants.dart
[Jira Ticket link](https://digit-discuss.atlassian.net/browse/IFIX-335?atlOrigin=eyJpIjoiYzI3ZjFkMmJjMWU0NDg2NjlhOTY0NjhhOGIzMTZmZTIiLCJwIjoiaiJ9)
> IFIX-335 : Expense Details Page

- frontend/mgramseva/android/app/src/main/AndroidManifest.xml
- frontend/mgramseva/lib/components/HouseConnectionandBill/ConsumerBillPayments.dart
- frontend/mgramseva/lib/providers/common_provider.dart
- frontend/mgramseva/lib/screeens/ConnectionResults/ConnectionDetailsCard.dart
- frontend/mgramseva/lib/screeens/Home.dart
- frontend/mgramseva/lib/widgets/ButtonGroup.dart
- frontend/mgramseva/lib/widgets/LabelText.dart
- frontend/mgramseva/lib/widgets/Notifications.dart
- Issue - URL launcher was  not Working in Android APP which causing user unable to Open Watsapp Application for Our App
Resolved - Added Permission in xml. 
- Issue - user was unable to identify file is downloaded or Not after clicking on Download in APP. 
Resolved - Added Flutter Download Plugin. Now user will see a notification on Start and can track of % of Download.
> added Permisson to Open Watsapp in App

- frontend/mgramseva/lib/model/connection/water_connections.dart
- frontend/mgramseva/lib/model/connection/water_connections.g.dart
- frontend/mgramseva/lib/providers/dashboard_provider.dart
- frontend/mgramseva/lib/repository/search_connection_repo.dart
- frontend/mgramseva/lib/screeens/dashboard/search_expense.dart
[Jira reference ticket](https://digit-discuss.atlassian.net/browse/IFIX-40?atlOrigin=eyJpIjoiZmM1ZTVhYWEyN2ZmNDE4M2JkOTU2NTE0YzVhNDQwNGQiLCJwIjoiaiJ9)
> IFIX-40 : UI : Revenue Dashboard  API integration

- frontend/mgramseva/lib/screeens/AddExpense/ExpenseDetails.dart
- frontend/mgramseva/lib/screeens/ConsumerDetails/ConsumerDetails.dart
- frontend/mgramseva/lib/screeens/ForgotPassword/ForgotPassword.dart
- frontend/mgramseva/lib/screeens/Login/Login.dart
- frontend/mgramseva/lib/widgets/Button.dart
- frontend/mgramseva/lib/widgets/TextFieldBuilder.dart
- frontend/mgramseva/lib/widgets/customAppbar.dart
Until all values are valid button button is disabled in Login
> IFIX-260: Login Screen-->Continue Button

- build/build-config.yml
buld config change for echallan-calcuator
> buld config change for echallan-calcuator

- build/build-config.yml
adding notification sms to build config
> adding notification sms to build config

- build/build-config.yml
adding build config for notification sms
> adding build config for notification sms

- frontend/mgramseva/README.md
Added Application Structure
Project Setup Commands
> Updated README file

- frontend/mgramseva/lib/screeens/ConnectionResults/ConnectionDetailsCard.dart
Added Localization for search Params
> mgramseva-patch-004

- build/build-config.yml
> Corrected Image ID for Vendor

- build/build-config.yml
added build config for egov-uesr-event
> added build config for egov-uesr-event

- frontend/mgramseva/lib/providers/bill_generation_details_provider.dart
- frontend/mgramseva/lib/providers/consumer_details_provider.dart
...months of financial year, for genrating demand and creating consumer
> PFM-2309:: Logic change for Jan, Feb and March

- frontend/mgramseva/lib/screeens/ConsumerDetails/ConsumerDetails.dart
Fixes for [https://digit-discuss.atlassian.net/browse/PFM-1773](https://digit-discuss.atlassian.net/browse/PFM-1773)
> PFM-1773::Allow alpha numeric and / - characters for Old Connection ID

- frontend/mgramseva/lib/screeens/ConsumerDetails/ConsumerDetails.dart
[https://digit-discuss.atlassian.net/browse/PFM-1773]
> PFM-1773::Input type number removed

- frontend/mgramseva/lib/providers/bill_payments_provider.dart
- frontend/mgramseva/lib/providers/household_details_provider.dart
[https://digit-discuss.atlassian.net/browse/PFM-1621](PFM-1621)
> PFM-1621::Cancelled Receipts should not be shown,

- frontend/mgramseva/lib/utils/role_actions.dart
- frontend/mgramseva/package.json
- frontend/mgramseva/pubspec.yaml
[PFM-2501](https://digit-discuss.atlassian.net/browse/PFM-2501)
[PFM-2501]: https://digit-discuss.atlassian.net/browse/PFM-2501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PFM-2501:: COLLECTION_OPERATOR role added to Create and Update Consumers

- frontend/mgramseva/lib/repository/ifix_hierarchy_repo.dart
> removed ts in DepartmentFetch Request

- municipal-services/ws-calculator/src/main/java/org/egov/wscalculation/service/DemandService.java
- municipal-services/ws-calculator/src/main/resources/application.properties
> payGovFix: Added Connection Type in PaymentLink to get it identified in UI

- municipal-services/echallan-services/src/main/java/org/egov/echallan/service/ChallanService.java
- municipal-services/echallan-services/src/main/java/org/egov/echallan/web/controllers/ChallanController.java
> PFM-1968: Created new API to update the challan but not to create any payment used for PSPCL

- municipal-services/echallan-services/src/main/java/org/egov/echallan/repository/ChallanRepository.java
Reverts egovernments/punjab-mgramseva#441
> Revert "PFM-3590: Added changes to show amount details for cancelled Challans"

- municipal-services/echallan-services/src/main/java/org/egov/echallan/repository/ChallanRepository.java
Reverts egovernments/punjab-mgramseva#443
> Revert "PFM-3590 Added changes to show amount details for cancelled Challans"

- frontend/mgramseva/lib/model/mdms/department.dart
- frontend/mgramseva/lib/model/mdms/project.dart
- frontend/mgramseva/lib/model/mdms/project.g.dart
- frontend/mgramseva/lib/providers/ifix_hierarchy_provider.dart
Reverts egovernments/punjab-mgramseva#454
> Revert "PFM-4053 fixed wrong department id in adapter-master-data search payload"

- municipal-services/ws-services/src/main/java/org/egov/waterconnection/service/WaterServiceImpl.java
This reverts commit 0727d74a804e807e034ffde3a99e8a11c14ac894.
> Revert "PFM-3541-CrashLoop added lazy annotation"

- frontend/mgramseva/lib/services/urls.dart
Reverts egovernments/punjab-mgramseva#689
> Revert "reverted mdms v2 to v1"

- frontend/mgramseva/lib/screeens/household_register/household_register.dart
https://digit-discuss.atlassian.net/browse/ISTE-25
> Household Register WhatsApp Share Allignment Issue FIx https://digit-discuss.atlassian.net/browse/ISTE-25 

- frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/textfields.scss
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/index.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/inbox/search.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/components/pageComponents/jurisdiction.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/EditEmployee/EditForm.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/Inbox.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/createEmployee.js
- frontend/micro-ui/web/micro-ui-internals/packages/modules/hrms/src/pages/index.js
BACK BTN,
SEARCH ALIGNMNET
AND OLD  HRMS CHANGES
> Hrms chnages prebuiild

- municipal-services/ws-calculator/src/main/java/org/egov/wscalculation/service/DemandService.java
Reverts egovernments/punjab-mgramseva#950
> Revert "removed billDate for update consumer"
